- name: RoboShop Project - Frontend
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: copy nginx-roboshop.conf
      ansible.builtin.copy:
        src: nginx-roboshop.conf
        dest:  /etc/nginx/default.d/roboshop.conf

    - name: clean old content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create App directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name:  download and extract Application content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html

    - name: Restart Nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: yes












#
#  echo -e "\e[36m <<<<<<<<<<<<<<<<<<<<<<<<     start and enable the nginx service     >>>>>>>>>>>>>>>>>>>>>>\e[0m"
#  systemctl enable nginx &>>${log}
#  systemctl restart nginx &>>${log}
#  func_exit_status