

#echo -e "\e[36mRemoving Default content\e[0m"
#rm -rf /usr/share/nginx/html/* &>>${log}
#func_exit_status
#
#echo -e "\e[36mDownloading Application Content\e[0m"
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>${log}
#cd /usr/share/nginx/html &>>${log}
#func_exit_status
#
#
#echo -e "\e[36mExtrating Application Content\e[0m"
#unzip /tmp/frontend.zip &>>${log}
#func_exit_status

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes